version: '3'

services:

  mysql:
    build: 
      context: ./mysql
      args: 
        MYSQL_VERSION: $MYSQL_VERSION
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 172.18.0.2
    restart: always
    container_name: mysql

  php: 
    build: 
      context: ./php
      args: 
        PHP_VERSION: $PHP_VERSION
    ports: 
      - 9000:9000
    depends_on:
      - mysql
    volumes: 
      - ./www:/var/www/html:cached
    networks:
      default:
        ipv4_address: 172.18.0.3
    restart: always
    container_name: php

  nginx:
    build: 
      context: ./nginx
      args: 
        NGINX_VERSION: $NGINX_VERSION
    ports: 
      - 80:8080
    depends_on: 
      - php
    volumes: 
      - ./www:/usr/share/nginx/html:cached
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/log:/var/log/nginx
    networks:
      default: 
        ipv4_address: 172.18.0.4
    restart: always
    container_name: nginx

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

 

