#!/bin/sh
set -e

if [ -e /var/www/html/.gitkeep ]; then
    rm /var/www/html/.gitkeep
fi

if [ "`ls -A /var/www/html`" = "" ]; then
  repository_url=https://mirrors.aliyun.com/composer
  cd /var/www/html
  composer create-project --stability=beta --no-install --no-progress --no-plugins --no-scripts --keep-vcs --repository-url=$repository_url flarum/flarum .
  composer config repo.packagist composer $repository_url
  composer require ffans/lang-simplified-chinese fof/profile-image-cro --no-update
  composer install --no-progress --no-plugins --no-scripts
  composer dump-autoload --optimize --no-dev
fi

exec "php-fpm"
